const js = require("@eslint/js");
const importPlugin = require("eslint-plugin-import");

module.exports = [
  js.configs.recommended,
  {
    files: ["src/**/*.js"],
    plugins: {
      import: importPlugin,
    },
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
      },
    },
    rules: {
      "array-bracket-spacing": ["error", "never"],
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { allowSingleLine: true }],
      "camelcase": ["error", { properties: "never" }],
      "comma-dangle": ["error", "always-multiline"],
      "comma-spacing": ["error", { before: false, after: true }],
      "comma-style": ["error", "last"],
      "curly": ["error", "multi-line"],
      "dot-location": ["error", "property"],
      "eol-last": ["error", "always"],
      "eqeqeq": ["error", "always", { null: "ignore" }],
      "func-call-spacing": ["error", "never"],
      "indent": ["error", 2, { SwitchCase: 1 }],
      "key-spacing": ["error", { beforeColon: false, afterColon: true }],
      "keyword-spacing": ["error", { before: true, after: true }],
      "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
      "new-cap": ["error", { newIsCap: true, capIsNew: false }],
      "no-array-constructor": "error",
      "no-multi-assign": "error",
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
      "no-new-object": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "error",
      "no-undef": "off",
      "no-unneeded-ternary": "error",
      "no-whitespace-before-property": "error",
      "object-curly-newline": ["error", { consistent: true }],
      "object-curly-spacing": ["error", "always"],
      "object-shorthand": ["error", "always"],
      "operator-assignment": ["error", "always"],
      "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
      "prefer-template": "error",
      "quotes": ["error", "single", { avoidEscape: true, allowTemplateLiterals: true }],
      "semi": ["error", "always"],
      "space-before-blocks": "error",
      "space-before-function-paren": ["error", "never"],
      "space-in-parens": ["error", "never"],
      "space-infix-ops": "error",
      "spaced-comment": ["error", "always", { markers: ["/"] }],
      "import/no-unresolved": "off",
      "import/named": "error",
      "import/default": "error",
      "import/export": "error",
      "import/no-duplicates": "error",
      "import/extensions": "off",
      "import/order": ["error", { "newlines-between": "always" }],
      "no-console": "off",
      "no-unused-vars": "warn",
      "no-plusplus": "off",
      "prefer-const": "warn",
      "no-use-before-define": "warn",
      "arrow-body-style": "off",
      "consistent-return": "warn",
      "prefer-destructuring": "warn",
      "max-len": ["warn", { code: 120 }],
      "no-param-reassign": "warn",
      "no-shadow": "warn",
    },
  },
  {
    ignores: [
      "node_modules",
      "dist",
      "*.min.js",
      "webpack.config.js",
      "postcss.config.js",
      "eslint.config.js",
    ],
  },
];
